### ISSUE TITLE
[BUG] Implosion does not work properly

### ISSUE THREAD

**Issue by IanJlafferty** [WittleWolfie/CharacterOptionsPlus#100]
**Describe the bug**
Implosion doesn't seem to work right in turn based mode, where you don't get the action to continue using the spell on following turns. On top of this it doesn't do the correct amount of damage, it does 10 times less. The damage it deals seems to be based on the class level rather then the caster level. So a cleric 14 mythic 5 should do 190 damage it only does 14. 

**To Reproduce**
1. Be a caster capable of casting implosion
2. Use implosion
3. See error

**Expected behavior**
Do 10 times caster level damage and cast it on other targets in turn based mode.
**Screenshots**
![image](https://user-images.githubusercontent.com/6034245/216242891-00d861c1-055c-4d3b-9a59-1abdd48415f9.png)

**Additional context**
[Manual_277_testing_spell.zip](https://github.com/WittleWolfie/CharacterOptionsPlus/files/10565511/Manual_277_testing_spell.zip)

**Comment by WittleWolfie** [comment]
What a typo on the damage (multiply by 1 not 10) xD Easy fix.

Regarding class level vs. CL, you said just Cleric 14 Mythic 5 but that is still CL 14. It would only be 19 if you are Angel path w/ merged spellbook.

It is using Caster Level so if you're seeing that not work it's gotta be some issue with merged spellbooks.

**Comment by IanJlafferty** [comment]
The character I used does have the merged spellbook, which is why I noticed the caster level difference.

**Comment by WittleWolfie** [comment]
To confirm: it is not merged by the mod, it is specifically Angel mythic?

**Comment by WittleWolfie** [comment]
Nevermind, I figured out the caster level issue.

**Comment by IanJlafferty** [comment]
That is good, though to still answer it was a cleric with the merged angel spellbook.

**Comment by WittleWolfie** [comment]
Alright the caster level thing is not going to get fixed. It's a pretty significant issue to resolve.

The turn based issue & damage will be fixed in next release (maybe today, definitely by Sunday)

**Comment by IanJlafferty** [comment]
Thanks for all your hard work. Just want to know if the damage will still scale as it does now.

**Comment by WittleWolfie** [comment]
It'll be 10 * Character Level... I guess Legend will go nuts :P

I might go back and fix the Caster Level issue but its a pain.

**Comment by IanJlafferty** [comment]
That is true about legend. No need to fix the caster level anytime soon, I am sure people will survive with it as is.

**Comment by WittleWolfie** [comment]
I lied, figured out a quick fix for CL!
