### ISSUE TITLE
[Feature] Elemental Rage Powers

### ISSUE THREAD

**Issue by WittleWolfie** [WittleWolfie/CharacterOptionsPlus#102]
https://www.d20pfsrd.com/classes/core-classes/barbarian/rage-powers/paizo-rage-powers/elemental-rage-su

**Comment by pheonix99** [comment]
This and its predecessor are merged into [Elemental Stance](https://aonprd.com/BarbarianUnchainedRagePowers.aspx?Type=Stance) for Unchained Barbarian which is what the game uses. Elemental Stance puts the whole cascade in one pick, too.

**Comment by WittleWolfie** [comment]
In TotF!
