### ISSUE TITLE
[Feature] Desna DFT: Desna's Shooting Star

### ISSUE THREAD

**Issue by pheonix99** [WittleWolfie/CharacterOptionsPlus#121]
**SRD Link**
[Shooting Star](https://aonprd.com/DeityDisplay.aspx?ItemName=Desna)
Morvarch never did the advanced tech and doesn't seem to be modding more - it would be nice to get this one in with the rest.

**Comment by Ardencroft** [comment]
I would also love this. Desna's divine fighting technique is so cheese I never had the evil in my soul that would be required to use it in a real game but its perfect for a CRPG!
