### ISSUE TITLE
[Feature] Modify Winter Patron with your new spells

### ISSUE THREAD

**Issue by Mythalar** [WittleWolfie/CharacterOptionsPlus#127]
Hey there 

First thing first thank you for all the new additions (and the mod menu is neat!) :)

With all your new, and sorely needed, new frost spells would it be possible to do some other tweaks to the winter patron?

- Frost fall as 2nd lvl spell instead of resist fire
- Ice Spears as 3rd lvl spell instead of protection from fire
- Freezing sphere as 6th lvl spell instead of Cold Ice Strike/Cone of cold

I guess thats the theme and those spells are, per RAW, on the [witch spell list](https://www.d20pfsrd.com/magic/all-spells/i/ice-spears/) or granted by the [winter patron](https://www.d20pfsrd.com/classes/base-classes/witch/witch-patrons/).

Hope thats not too much a request :)

**Comment by CaptOcto** [comment]
Maybe put Ice Storm at level 3 as per RAW. Not sure what could go into the level 4 slot in that case though...

**Comment by WittleWolfie** [comment]
Okay got some clarification as to why this is so weird. The winter patron grants a bunch of spells at an earlier level.

**Comment by WittleWolfie** [comment]
Fixed with next release
