### ISSUE TITLE
[BUG] Cannot select Winter Witch Spellbook for Loremaster

### ISSUE THREAD

**Issue by Cylush** [WittleWolfie/CharacterOptionsPlus#129]
**Attach a Bug Report**
https://github.com/WittleWolfie/CharacterOptionsPlus#reporting-problems

**Describe the bug**
Winter Witch archetype is entirely unselectable for Loremaster's Spellbook selection.

**To Reproduce**
1. Take 5 levels in Winter Witch.
2. Select the prerequisite Feats.
3. See screenshot.

**Expected behavior**
Winter Witch Spellbook shows up as the only option.

**Screenshots**
![image](https://user-images.githubusercontent.com/32019955/219368535-924258c7-1792-408a-9267-b166490a5766.png)

**Comment by WittleWolfie** [comment]
Turns out, this is a conflict with TabletopTweaks-Base. They replace most of the Loremaster class so when you have the Loremaster features enabled it doesn't work. Will fix.

**Comment by WittleWolfie** [comment]
Fix incoming
