### ISSUE TITLE
[BUG] Eldritch Heritage Arcane Bond Bug

### ISSUE THREAD

**Issue by OnmiKhaos** [WittleWolfie/CharacterOptionsPlus#132]
**Attach a Bug Report**
https://github.com/WittleWolfie/CharacterOptionsPlus#reporting-problems

**Describe the bug**
Using the Eldritch Heritage - Arcane Feat, to gain Arcane Bond, tried to restore the spell, it didn't work, giving the error "Out of resources: BloodlineArcaneItemBondResource

1. Give Nenio the Eldritch Heritage Feat, Select the Arcane Bond
2. Expend a Spell
3. Attempt to restore spell using the Arcane Bond feature

**Expected behavior**
Spell resoted

**Screenshots**

**Additional context**
Yes, Cantrips are also showing the Arcane bond as available

Additional mods:
Added Feats
Auto Mount
Bubble Buffs
Bubble Tweaks
Dark Codex
Enhanced Inventory
Finnean Tweaks
Fix Alignment Shifts
Kineticist Elements Expanded
Levelable Aivu
Madison's Metagaming
Martial Excellence
Medium Class
Microscopic Content Expansion
Miscellaneous Tweaks and Fixes
Mod Menu
More Bulk Sell
Phoenix's Cantrips, More Cantrips
Multiple Archetypes
Mystical Mayhem
Mythic Arcanist
Phoenix's Cantrips
WOTR Resource Unification Mod
Respec Mod
Spellbook Merge
Spell Pouch
TTT Base
TTT Core
TTT Mythic Rework
Toggleable Throwable Weapons
Tome of the Firebird
Toybox
VA2
Weapon Focus Plus
AC (Homebrew Archetypes)
AC Testing Grounds (Homebrew Archetypes)
Homebrew Archetypes
Ninja Class
![Wrath_2cKY7Z07e7](https://user-images.githubusercontent.com/61093352/222507394-960cda2a-9890-4bdc-993a-14d469087df6.png)
[Manual_27_Gwerm_s_Mansion__18_Arodus__VIII__4715__01_03_05.zip](https://github.com/WittleWolfie/CharacterOptionsPlus/files/10874157/Manual_27_Gwerm_s_Mansion__18_Arodus__VIII__4715__01_03_05.zip)

**Comment by WittleWolfie** [comment]
Unable to repro. The way the code implementation works this is exactly the ability granted by the Arcane Bloodline (i.e. unchanged). Given it works in my setup this looks like another mod is breaking it.

The next step if you can is to try acquiring Arcane Bloodline normally and see if you run into the same issue. If so it's just another mod; otherwise there could be a mod conflict though that would be very odd.

**Comment by WittleWolfie** [comment]
Given that this is probably a conflict w/ another mod I'm going to close out for now. If you can determine that it's a mod conflict with COP + Mod (i.e. Arcane Bloodline works w/ Mod enabled, COP enabled, but not both) please re-open.
