### ISSUE TITLE
[BUG] Dimensional Blade has no effect

### ISSUE THREAD

**Issue by NosVladimir** [WittleWolfie/CharacterOptionsPlus#133]
**Attach a Bug Report**
[Save and bug report.zip](https://github.com/WittleWolfie/CharacterOptionsPlus/files/10897397/Save.and.bug.report.zip)

**Describe the bug**
Dimensional blade has no effect. After use, melee attacks are not touch attacks.

**To Reproduce**
1. Start a new game with a cleric, choose animal domain so there's something to make a charge attack to
2. Use ToyBox to level up the MC to level 8 and give him a club. Then prepare dimensional blade and take a rest using Toybox. Select whatever animal companion
3. Cast dimensional blade, then immediately make a charge towards the animal companion. Resulted attack still calculates the natural armor bonus of the companion (see screenshot below)

**Expected behavior**
The attack should be a touch attack, ignoring natural armor bonus

**Screenshots**
![20230306105943_1](https://user-images.githubusercontent.com/32335397/223094318-1f778c84-8c31-4e88-939e-380b5538d380.jpg)

**Additional context**
Save and bug reported attached in the zip file ablve
Other mods:
Mewsifer Console 1.1.6
Mewsifer Console Menu 1.1.6
Mod Menu 1.3.0
Tabletop Tweaks Base 2.4.6
Tabletop Tweaks Core 0.5.7
ToyBox 1.4.21

**Comment by WittleWolfie** [comment]
Also excellent report :) Really appreciate the log & save file!

**Comment by WittleWolfie** [comment]
Haven't tested yet but took a glance at the code + screenshot. I think this is mostly WAI: due to the way AC / Attack calculations are done in game, right now Dimensional Blade adds to your attack bonus to compensate for AC. Note that you have a +9 bonus from Dimensional Blade.

However, the "Natural armor stackable" bonus looks like it should probably be covered as well and it is not. It also might be possible for me to revisit this implementation and come up with something more reliable.

**Comment by NosVladimir** [comment]
> Thanks for the report. Is this on the beta branch?

No it's on the main branch with game version 2.0.7o.

> Also excellent report :) Really appreciate the log & save file!

You are welcome :) I understand the pain when people don't give enough details when reporting a bug.

> Dimensional Blade adds to your attack bonus to compensate for AC.

I actually ignored that! How did I not see the bonus... But it's a good spot anyway since I also don't know the source of the mysterious 'Natural armor stackable'. Haven't looked at it yet but I suppose that's something added by Tabletop Tweaks?

As a suggestion, this spell sounds like it should work in the same way as the Magus arcana Accurate Strike. Would it be possible to copy-paste the code of that? I'm not a modder so not sure if the official code can be viewed, but if it can then that's probably the simplest and most reliable way to implement the spell.

**Comment by WittleWolfie** [comment]
Yeah I'll take a second pass on it and see if I can do something like that.

**Comment by WittleWolfie** [comment]
Good thinking on the Magus Arcana, I think I couldn't find it or forgot it existed initially. I used the design of that so in the update once the patch drops this will be fixed to actually change to a touch attack.
