### ISSUE TITLE
[BUG] Witch - Winter Witch can't learn non-fire Dragonbreath (Elemental Patron)

### ISSUE THREAD

**Issue by CaptOcto** [WittleWolfie/CharacterOptionsPlus#135]
**Attach a Bug Report**
https://github.com/WittleWolfie/CharacterOptionsPlus#reporting-problems

**Describe the bug**
Winter Witch with additional patron: Elemental Patron can't learn Dragon Breath (non Fire varieties)

**To Reproduce**
1. Choose Additional Patron: Elemental as Winter Witch Archetype
2. Be level 8+
3. No Dragonbreath available (Cold or otherwise)

**Expected behavior**
Winter Witch archetype with should be able to learn non-fire varieties of Dragonbreath.

**Screenshots**

**Additional context**

**Comment by WittleWolfie** [comment]
What is "Additional Patron"? I can't find any such option.

**Comment by WittleWolfie** [comment]
Ahh, this is a mythic ability added by TabletopTweaks-Base. I might fix this but the fix is actually to disallow Elemental patron.

**Comment by CaptOcto** [comment]
Hi thanks for looking into this! Sorry I didn't realise that Second Patron
was a TTT feat.

Guess I'll stick with the Loremaster path to get Icy Prison, Mass!

**Comment by WittleWolfie** [comment]
Yeah no worries. I'll probably patch for TTT anyways.

**Comment by WittleWolfie** [comment]
Yaaay. Fix incoming!
