### ISSUE TITLE
[Feature]Please clarify: Does Energy Channel only apply to damage to 1 creature?

### ISSUE THREAD

**Issue by CaptOcto** [WittleWolfie/CharacterOptionsPlus#142]
**SRD Link**
[Provide a link to the feature on [d20 PF SRD](https://www.d20pfsrd.com/) or [AoN PRD](https://www.aonprd.com/).](https://www.d20pfsrd.com/feats/general-feats/energy-channel/)

Just reading through the description and wondering if it is possible to apply the damage from Energy Channel more than once per attack via anything like:
- Cleave
- Great Cleave
- Cleaving Finish
- Any items (Wide Sweep, Ricocheting Heavy Crossbow etc) 
- Zippy Magic (perhaps through a Touch Spell and/or on a character with Spellstrike?)
- Manyshot
- Rapid Shot
- etc.

**Comment by CaptOcto** [comment]
Is it possible to use Lich Danse Macabre negative energy channel with Energy Channel?

**Comment by Ardencroft** [comment]
This effect lasts for your next three weapon attacks or until the end of combat, whichever comes first.

**Comment by WittleWolfie** [comment]
The way this is implemented it will trigger every time the game triggers `RuleCalculateDamage` for weapon damage. I would expect it to apply in the specified cases but I haven't tested.

**Comment by CaptOcto** [comment]
So a single Great Cleave against 3 enemies would drain all 3 charges?

**Comment by WittleWolfie** [comment]
That's what I'd expect. I think arguably it shouldn't use the charges but fixing it would be pretty annoying.

**Comment by CaptOcto** [comment]
Yeah I was reading trying to find a way to make the feat worthwhile but RAI is pretty clear as all the abilities state things like "make an attack" or "make an extra attack" which would trigger the use of energy channel.

I also misinterpreted the words that it was adding d6s of Elemental damage but it's only 2 points of energy damage per d6 of channel which further nerfed it but it made me wonder if it would then be multiplied on crits (as its not a variable)?
