### ISSUE TITLE
[BUG]Reach Frostbite not working with Ranged Spell combat

### ISSUE THREAD

**Issue by CaptOcto** [WittleWolfie/CharacterOptionsPlus#144]
As above I just tested this once and couldn't get a Magus Archer to fire with Frostbite, is this something that is fixable?

**Comment by WittleWolfie** [comment]
Probably. I haven't been actively modding for a bit but I'll take a look as I get back into it.

**Comment by WittleWolfie** [comment]
Also for context can you provide a mod list?

**Comment by CaptOcto** [comment]
Dark Codex (everything disabled except for Prodigious Two Weapon Fighting Feat)
Tabletop Tweaks/Base/Core/Flanking
Toybox
Added Feats
Alternate Human Traits
Auto Mount
Bubble Buffs
Bubble Tweaks
Character Options+
Mewsifer Console
Mewsifer Console MEnu
Mod Menu
Multiple Archetypes
Respec Mod
Weapon Focus Plus

**Comment by WittleWolfie** [comment]
Looked into this more and I'm not planning to fix. The way they implemented Ranged Spellstrike doesn't work w/ Reach Touch spells so this would be a larger change.

**Comment by CaptOcto** [comment]
Thanks for having a look, appreciate all your work, can't wait to see the new mod you've been working on!
