### ISSUE TITLE
[Feature]Extra Incense Discovery

### ISSUE THREAD

**Issue by CaptOcto** [WittleWolfie/CharacterOptionsPlus#145]
Not a tabletop request as Incense Synthesisor is an Owlcat original but after playing with the class through DLC1 the only thing missing is an opportunity to get extra Incense Discoveries to flesh out the signature ability.

Could an "Extra Incense Discovery" feat be added?

**Comment by WittleWolfie** [comment]
Just extra discovery for Incense Synthesizer? I'll consider it.

You probably noticed I'm on a bit of a hiatus on this, I'm focused on implementing a new mod after which I'll come back to CO+ and work through the backlog.

**Comment by CaptOcto** [comment]
I thought to myself how hard can it be to make one feat so installed
Microsoft Visual Studio Community and looked at a couple of mods and that
was as far as I got....

**Comment by CaptOcto** [comment]
With the help of some of the amazing guys in the discord channel I managed to make this mini mod so testing it out on a run right now with self imposed level requirements (allowing myself to go wide on Incense but not tall). If I think it's balanced I'll try to figure out how to apply level requirements as appropriate.

**Comment by WittleWolfie** [comment]
Very cool, glad to hear it!
