### ISSUE TITLE
[BUG] Hurtful crashes executioner's assassinate action

### ISSUE THREAD

**Issue by alkdnvwoeivn** [WittleWolfie/CharacterOptionsPlus#147]
With hurtful toggled on, the executioner's assassinate action leads to a game freeze. Possibly because a successful assassinate demoralizes all nearby enemies, much like dreadful carnage. My executioner also has dreadful carnage, so maybe that's contributing to the problem as it's demoralizing everyone twice.

With hurtful toggled off, it works fine.

It's not a huge deal to remember to toggle off hurtful before assassinating someone, but thought I'd report the bug anyway.

**Comment by WittleWolfie** [comment]
Can you post a log?

**Comment by alkdnvwoeivn** [comment]
Sure
[GameLogFull.txt](https://github.com/WittleWolfie/CharacterOptionsPlus/files/11240879/GameLogFull.txt)

**Comment by WittleWolfie** [comment]
I haven't been able to reproduce this issue. Can you provide a game log after enabling verbose logging? Include Player.log as well.

![image](https://user-images.githubusercontent.com/399167/232328356-ac90a8ac-a693-4394-a9bd-c62892306b3e.png)

**Comment by WittleWolfie** [comment]
A save file & mod list could also be helpful.

**Comment by alkdnvwoeivn** [comment]
I suspect your executioner needs to be at least level 14, that's when they get the demoralize on assassinate ability.

Here's a verbose log and a save file (the executioner is my MC, first character in the list). I don't have a Player.log, the only logs there are combatLog, GameLog, GameLogFull, GameLogFullPrev, and GameLogPrev.

I'm using the following mods:
Character options+, Mod menu, TTT (core, base, mythic reworks), Expanded content, Homebrew archetypes, Toybox, Bubble buffs, Barley respec mod, Scaling cantrips, Spar's sorcerous sundries, Spellpouch

[GameLogFull.txt](https://github.com/WittleWolfie/CharacterOptionsPlus/files/11254933/GameLogFull.txt)
[Manual_127_AssassinateBug.zks.zip](https://github.com/WittleWolfie/CharacterOptionsPlus/files/11254938/Manual_127_AssassinateBug.zks.zip)

**Comment by WittleWolfie** [comment]
I can try the save file. I was testing w/ a level 14 executioner but I suspect it was an issue w/ the test setup (spawning enemies w/ ToyBox was causing weird issues).

Hmm, the CO+ logging happens in Player.log which is the UMM log file. Usually it's in the same AppData folder as GameLog. Maybe yours is logging elsewhere? If you can find it that is helpful, otherwise I'll see if I can use your save file.

**Comment by WittleWolfie** [comment]
Looks like it's caused by Furious Focus & Paired Opportunists.

**Comment by WittleWolfie** [comment]
Figured it out. The problem is that Hurtful relies on a fixed resource (Swift) to prevent it from chaining. However, the game doesn't let you spend a swift action if you're "not in combat" and assassinate is causing that to trigger.
