### ISSUE TITLE
Additional Litany spells & Paladin sacrifice

### ISSUE THREAD

**Issue by knk101** [WittleWolfie/CharacterOptionsPlus#148]
https://www.d20pfsrd.com/magic/all-spells/l/litany-of-righteousness/

https://www.d20pfsrd.com/magic/all-spells/l/litany-of-defense

https://www.d20pfsrd.com/magic/all-spells/p/paladin-s-sacrifice

This is an iconic Paladin spell i think should be on their spell list

**Comment by WittleWolfie** [comment]
Paladin's Sacrifice is definitely a no, but I like both litany's.

**Comment by knk101** [comment]
Thank you for considering :)
