### ISSUE TITLE
[BUG] Horrific Doubles removes surprise rounds

### ISSUE THREAD

**Issue by JamesEhren** [WittleWolfie/CharacterOptionsPlus#150]
With horrific doubles up, combat starts as soon as an enemy is in view.  This eliminates the possibility of surprise rounds for the player.  Not sure if this is truly a bug and it should be functioning like Frightful Aspect/Archon's Aura, or just wildly inconvenient.

**Comment by WittleWolfie** [comment]
It's an interesting point. Frightful Aspect & Archon's Aura will aggro enemies as well but I suspect you don't run into it often because the range is low.

Not sure how to handle this one right now. It should aggro enemies but it is also inconvenient because the range on it is so large.

**Comment by JamesEhren** [comment]
Small update.  I was trying to figure out who could use HD as is, because losing the surprise round isn't really an option.  I figured if it is was working off of sight, then it could be useful for a full-speed while stealthed character.  One that could always be stealthed out of combat and still keep up with the party.  And it worked! Kind of. 

With HD cast and stealthed while with the party, the HD effect would still immediately affect the enemies but they would no longer aggro until I or a party member initiated by attacking or entering aggro range.  The HD character could also de-stealth after the HD-effect was applied and walk around the periphery of the enemy without triggering aggro.  I'm guessing these are both just because of how the game works, can't be changed, and honestly will be fine for almost everyone.

So as is, this is a Woljif spell.  Which is somewhat disappointing as its no longer a general upgrade for mirror image... but its nice to add to a niche!  As opposed to a change to how the spell works (a smaller aura like Frightful Aspect/Archon's Aura) I would request simply a note at the bottom of the spell description noting that enemies will aggro if the user is not hidden. It's just too reasonable to assume that an unaggro'd demon group doesn't "see you" even if you can see them.  After all, they would be attacking you if they saw you, whether you had HD up or not.  They're not in the worldwound to mind their own business.  Or, rather, attacking you on sight _is_ their business.

Unless you intended to make it a general upgrade to mirror image, then going the aura route seems like a reasonable change to the spell to make it work in the context of the crpg.
