### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Belle-End** [WittleWolfie/CharacterOptionsPlus#153]
**Describe the bug**
Companion religions doesn't show under "Class" in character screen.

**Comment by WittleWolfie** [comment]
Can you clarify? I'm not sure I understand the problem. CO+ doesn't alter religion or class (or the UI) in any way.

Also, please provide the details described here: https://github.com/WittleWolfie/CharacterOptionsPlus#reporting-problems

**Comment by Belle-End** [comment]
Does this not att a bunch of religions from tabletop?
Did I mix up this mod with another one? 😗

I'll check when I get home but if it is this one the issue is that the religion of companions doesn't show up in the interface under the class-tab. But the bonuses apply so no biggie I guess.

**Comment by WittleWolfie** [comment]
Most likely you're thinking [Expanded Content](https://github.com/ka-dyn/ExpandedContent) which adds a lot of deities.
