### ISSUE TITLE
[Suggestion] Change Dreadful Carnage prerequisite to Furious Focus instead of Dazzling Display

### ISSUE THREAD

**Issue by alterasc** [WittleWolfie/CharacterOptionsPlus#155]
[Dreadful Carnage](https://www.d20pfsrd.com/feats/combat-feats/dreadful-carnage-combat/) in TT requires Furious Focus as prerequisite. Owlcat changed it to require Dazzling Display as they don't have Furious Focus (later FF).

With FF added, Dreadful Carnage prerequisites could be changed to require FF and not Dazzling. Perhaps this could be togglable in mod settings.

**Comment by WittleWolfie** [comment]
Fixed in next release
