### ISSUE TITLE
[BUG] Signature Skill: Persuasion additional effect checks are not tagged as fear.

### ISSUE THREAD

**Issue by alterasc** [WittleWolfie/CharacterOptionsPlus#156]
**Attach a Bug Report**
https://github.com/WittleWolfie/CharacterOptionsPlus#reporting-problems

**Describe the bug**
Skill unlock Persusasion allows additional effect if you succeed on demoralizing the opponent.
Effect at 5 ranks:
> 5 Ranks: If you exceed the DC to demoralize a target by at least 10, is is frightened for the first round of the effect.
> A Will save (DC = 10 + Persuasion) negates these additional effects

That save does not take into account modifiers against fear effects.

**To Reproduce**
1. Pick a target
2. Cast Blessing of Courage and Life on them (which provides +2 to save against fear)
3. Demoralize, exceeding DC by at least 10
4. See that in saving throw target makes there is no +2 bonus.

**Expected behavior**
modifiers to saving throws against applicable fear descriptors (fear, mind affecting, maybe more) should apply.

**Screenshots**

**Additional context**

**Comment by WittleWolfie** [comment]
Fixed in next release.
