### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Bredwh** [WittleWolfie/CharacterOptionsPlus#157]
[CharacterOptions+.zip](https://github.com/WittleWolfie/CharacterOptionsPlus/files/12866154/CharacterOptions%2B.zip)

I was going through each mod I have one by one to see which was giving errors and warnings by itself at startup (though I also had ModMenu, Mewsifer Console, and Mewsifer Console Menu. And often TT Core and Base since many mods rely on those). This gave an error about DLC 4, which a few other mods did as well but most didn't. It also gave many warnings about blueprints failing validation.

To reproduce go to ModFinder and have active this mod and only ModMenu, Mewsifer Console, Mewsifer Console Menu, TT Core and TT Base. Then start WotR and wait until get to main start screen. The warnings and error should be in the console by then.

**Comment by WittleWolfie** [comment]
Thanks for the report, I'll take a look. The warnings are a known issue but shouldn't cause any issues. Most of the warnings are because of Owlcat bugs.
