### ISSUE TITLE
[BUG] Some feats not beeing functional in 2.2.1a

### ISSUE THREAD

**Issue by L4wlight** [WittleWolfie/CharacterOptionsPlus#158]
**Describe the bug**
Some feats don't show up anymore after the last patch: [Divine Fighting Technique](https://www.aonprd.com/FeatDisplay.aspx?ItemName=Divine%20Fighting%20Technique), [Eldritch Heritage](https://www.d20pfsrd.com/feats/general-feats/eldritch-heritage/) ( [Improved](https://www.d20pfsrd.com/feats/general-feats/improved-eldritch-heritage/) and [Greater](https://www.d20pfsrd.com/feats/general-feats/greater-eldritch-heritage/)), [Energy Channel](https://www.d20pfsrd.com/feats/general-feats/energy-channel/), [Signature Skill](https://www.d20pfsrd.com/feats/general-feats/signature-skill-general/)

**To Reproduce**
1. Tested with my other mods & CharacterOptionsPlus 
2. Tested with only Mod Menu & CharacterOptionsPlus installed

**Expected behavior**
The feats to show up

**Screenshots**
![Divine Fighting Techniques](https://github.com/WittleWolfie/CharacterOptionsPlus/assets/126925802/e68b546a-7a60-4307-ba9f-f28faa3b5c72)
![Eldritch Heritage](https://github.com/WittleWolfie/CharacterOptionsPlus/assets/126925802/446ad1c5-57ab-4c2f-9fe8-0a7c0f934c34)
![Energy Channel](https://github.com/WittleWolfie/CharacterOptionsPlus/assets/126925802/f06748e5-8709-43f4-92c4-392f60df8a0d)
![Signature Skill](https://github.com/WittleWolfie/CharacterOptionsPlus/assets/126925802/bd781b77-19e9-422c-bda8-b5eebc7814e2)

**Comment by WittleWolfie** [comment]
Thanks for the report! I should be able to fix this weekend.

**Comment by WittleWolfie** [comment]
Found the problem, fix will be up in a few hours.
