### ISSUE TITLE
Winter Witch prestige doesn't give Hex progression to Winter Witch archetype[BUG]

### ISSUE THREAD

**Issue by CaptOcto** [WittleWolfie/CharacterOptionsPlus#160]
**Attach a Bug Report**
https://github.com/WittleWolfie/CharacterOptionsPlus#reporting-problems

**Describe the bug**
Respecced my Lord of Nothing character into a Winter Witch 5/Winter Witch 6 character and for some reason I didn't get any hexes after the initial 2 so at level 11 the character only has 2 hexes.

**Screenshots**

![202401261440135634](https://github.com/WittleWolfie/CharacterOptionsPlus/assets/119921959/2fcb05fc-4d7b-439d-9729-dedb33454e57)
![202401261440190113](https://github.com/WittleWolfie/CharacterOptionsPlus/assets/119921959/80fce9a6-5115-42b2-ac38-9644cdfe9412)

**Comment by WittleWolfie** [comment]
Fixed in next release
