### ISSUE TITLE
Still not getting hexes on Winter Witch/Winter Witch[BUG]

### ISSUE THREAD

**Issue by CaptOcto** [WittleWolfie/CharacterOptionsPlus#163]
**Attach a Bug Report**
https://github.com/WittleWolfie/CharacterOptionsPlus#reporting-problems

[nklufzth.zip](https://github.com/WittleWolfie/CharacterOptionsPlus/files/14189209/nklufzth.zip)

**Describe the bug**

**To Reproduce**
1. Make a Winter Winter/Winter Witch.
2. Level up to 5/10 (CL 15).
3. See error: no additional hexes.

**Expected behavior**
Should accrue 5 additional hexes over 10 levels of Winter Witch prestige class.

However this might be a WotR issue as I've also experienced the issue with Shaman and Stigmatised Witch not getting any hexes.

**Screenshots**

**Additional context**

**Comment by WittleWolfie** [comment]
I can't reproduce this error. Try with the latest version and if you're still having issues share a save file and mod list that reproduces the issue.
