### ISSUE TITLE
Arrowsong Minstrel not correctly determining BAB for Prestige Classes [BUG]

### ISSUE THREAD

**Issue by Ardencroft** [WittleWolfie/CharacterOptionsPlus#164]
Arrowsong Minstrel says "for the purpose of meeting the requirements of combat feats and prestige classes, an Arrowsong minstrel treats her bard level as her base attack bonus (in addition to base attack bonuses gained from other classes and Hit Dice)." under the arcane archery ability. It does not seem to be calculating correctly. For instance, at level 2 those levels should count as 2 BaB, but it is only calculating as 1.

**Comment by WittleWolfie** [comment]
I'm not able to reproduce this. If you still have issues please share a save file & mod list that recreates the problem.
