### ISSUE TITLE
[BUG] Mythic Inspiration Breaks Skald's Vigor

### ISSUE THREAD

**Issue by Vaeliorin** [WittleWolfie/CharacterOptionsPlus#165]
**Describe the bug**
Picking Mythic Inspiration causes Skald's Vigor (and Greater Skald's Vigor) to stop functioning.

**To Reproduce**
Take Skald's Vigor, take Mythic Inspiration, Skald's Vigor stops healing

**Expected behavior**
Skald's Vigor continues to work with Mythic Inspiration

**Additional context**
It's not really a huge issue, and I totally understand if you don't want to fix it, given that you're no longer actively working on Wrath modding.

**Comment by WittleWolfie** [comment]
I probably know what's wrong. No promises but if I get the motivation to go back to bugfixes I'll revisit.

Chances are I'll be back briefly when they do the next big patch / DLC drop to make sure everything works.
