### ISSUE TITLE
[BUG] Dreadful Carnage requires Furious Focus 

### ISSUE THREAD

**Issue by Gyrados15** [WittleWolfie/CharacterOptionsPlus#171]
The game is telling me Dreadful Carnage requires Furious Focus as a pre-requisite, but I know you made changes to this in "[BUG] Furious Focus is duplicate of Focused Strike #166 " and Indeed Furious Focus is not an option to be selected for me :

![image](https://github.com/WittleWolfie/CharacterOptionsPlus/assets/129967365/ddacd7f0-b5e8-453a-8f8b-725413c95ae6)

![image](https://github.com/WittleWolfie/CharacterOptionsPlus/assets/129967365/afb6eccb-0a89-4ab0-82c2-302653b64a72)

![image](https://github.com/WittleWolfie/CharacterOptionsPlus/assets/129967365/11301c16-d2ab-4dcf-b88f-1b371a947c8f)

**Comment by WittleWolfie** [comment]
Oops. I'll fix that. I'm returning to the fold though I'll only be fixing bugs I think... modding is a trap.

**Comment by Gyrados15** [comment]
Haha, thanks XD
Kind Regards

Gary Shaw
