### ISSUE TITLE
Class with Animal Companion Can Cast Personal Spells on the Animal Companion

### ISSUE THREAD

**Issue by zigma9114** [WittleWolfie/CharacterOptionsPlus#54]
More of a feature addition instead of content, but if possible can you have this feature added to the mod? In TT Druid and other classes with Animal Companion could cast personal spells to their companion. For Druid for example it is important to be able to cast their Aspect spells on the companion

**Comment by WittleWolfie** [comment]
Not committing to it but I'll leave this open for consideration.

**Comment by WittleWolfie** [comment]
Flagged this as a maybe. It's something I'd still like to do but as you can see, I have a lot of those! Once I get through all the planned content I'll start working on the maybe items. That's probably going to be some time next year.

**Comment by zigma9114** [comment]
> Flagged this as a maybe. It's something I'd still like to do but as you can see, I have a lot of those! Once I get through all the planned content I'll start working on the maybe items. That's probably going to be some time next year.

that's great to hear! this feature is one of the biggest missing class feature for Druid and Animal Class companions in general so I am happy to hear that you are planning for it in the future

**Comment by WittleWolfie** [comment]
Implementation is done, this will go out with the next release.
