### ISSUE TITLE
Energy Channel (pretty please)

### ISSUE THREAD

**Issue by knk101** [WittleWolfie/CharacterOptionsPlus#57]

**Comment by WittleWolfie** [comment]
This looks cool. Definitely will consider.

**Comment by knk101** [comment]
Thank-you I think so too 😃

**Comment by WittleWolfie** [comment]
Flagged this as a maybe. It's something I'd still like to do but as you can see, I have a lot of those! Once I get through all the planned content I'll start working on the maybe items. That's probably going to be some time next year.

**Comment by knk101** [comment]
No worries best of luck - everything you add is making the game that much better :)

**Comment by WittleWolfie** [comment]
Implementation is done, waiting on icons and the next release.
