### ISSUE TITLE
Adding winter witch archetypes of the witch

### ISSUE THREAD

**Issue by CanMik** [WittleWolfie/CharacterOptionsPlus#59]
Hello is it possible to add the archetypes of witch (winter witch) https://www.d20pfsrd.com/classes/base-classes/witch/archetypes/paizo-witch-archetypes/winter-witch/ witch will help a lot the winter witch build :D

**Comment by WittleWolfie** [comment]
Given there is Elemental Witch (Archetype) and Winter Witch (Prestige Class) this doesn't seem that interesting. Thoughts?

**Comment by CanMik** [comment]
This archetype is even better than any archetype for witch, because of the
hex that allow to use any spells as cold magic. And it combines very well
with the prestige class.

Le ven. 9 sept. 2022 à 17:48, WittleWolfie ***@***.***> a
écrit :

**Comment by WittleWolfie** [comment]
That's a great point. I'll leave this open as a maybe--as I understand it actually implementing the switch to cold magic is difficult but we'll see what happens.

**Comment by CanMik** [comment]
Cheers I will look forward it

Le ven. 9 sept. 2022 à 17:57, WittleWolfie ***@***.***> a
écrit :

**Comment by WittleWolfie** [comment]
FYI I am planning to do this. No Frostfoot Hex but Frozen Caress hopefully. Aside from that I will for sure build this archetype, going to use it for my run :)

**Comment by CanMik** [comment]
Glad to hear that , we gonna throw some ice touch spells shenanigans =)
