### ISSUE TITLE
latest update

### ISSUE THREAD

**Issue by Gwendovescry** [WittleWolfie/CharacterOptionsPlus#61]
save file won't load anymore

**Comment by WittleWolfie** [comment]
https://github.com/WittleWolfie/CharacterOptionsPlus#reporting-problems

Additionally can you provide more details. Did you have the mod installed previously and upgrade?

**Comment by Gwendovescry** [comment]
I can't run mewsifer. It slows the game down so much for me. Just getting
to the main menu takes 10 minutes. When I try to do something like go to
inventory or put something in a chest it takes a solid minute per action. I
cannot use it.

But I had character options+ installed and it was working perfectly fine
yesterday. I woke up this morning, updated, and now as soon as it finishes
loading the save file it just goes back to the main menu

**Comment by WittleWolfie** [comment]
Interesting. Are you using the Mewsifer from Nexus or GitHub? The version on GitHub should have negligible impact on perf.

If it is the one on GitHub can you just run the game as far as you can, then share these logs:

`%UserProfile%\AppData\LocalLow\Owlcat Games\Pathfinder Wrath of the Righteous\Player.log`
`%UserProfile%\AppData\LocalLow\Owlcat Games\Pathfinder Wrath of the Righteous\GameLogFull.txt`

Similarly, after reproing a load failure w/ COP you can do that.

**Comment by WittleWolfie** [comment]
Issue is caused by this GUID: `a8e28632b3aa4931ab28095a4be12afc`. This is not coming from COP.

Regarding Mewsifer is the issue when you're running the console or just with the mod active? You can generate the bug report w/o the console being active.

**Comment by WittleWolfie** [comment]
Well the other log is more clear:

```
Failed loading blueprint: C:/Users/apola/AppData/LocalLow/Owlcat Games/Pathfinder Wrath Of The Righteous\Modifications\TheSwarmFiles\Blueprints\SwarmFilesDodge.jbp
```

This is probably the mod causing your issues.

**Comment by Gwendovescry** [comment]
[Player.log](https://github.com/WittleWolfie/CharacterOptionsPlus/files/9601111/Player.log)
[GameLogFull.txt](https://github.com/WittleWolfie/CharacterOptionsPlus/files/9601112/GameLogFull.txt)
The only thing I changed between the game not loading properly was updating COP. I know very little about computer stuff so I don't know what that GUID thing means. Even with swarm files uninstalled however, it still will not load the save. Regarding mewsifer I can have it installed I just can't have it turned on. Below this I've included the same logs but without swarm files.
[Player.log](https://github.com/WittleWolfie/CharacterOptionsPlus/files/9601143/Player.log)
[GameLogFull.txt](https://github.com/WittleWolfie/CharacterOptionsPlus/files/9601144/GameLogFull.txt)

**Comment by WittleWolfie** [comment]
Got it. So with it installed you can still go through the bug report process.

The problem is that TheSwarmFiles is broken. It is failing to load a blueprint which is referenced in your save, so you cannot load that save. You'll need to reach out to the creator of that mod.

**Comment by Gwendovescry** [comment]
Ok but why would that suddenly be an issue if nothing changed with it?

**Comment by WittleWolfie** [comment]
Based on the error, The Swarm Files was built against an older game version. The underlying game code changed and their mod is not longer compatible.

**Comment by WittleWolfie** [comment]
If you don't get a response you can ask for help on [Discord](https://discord.com/invite/owlcat). Either you might convince someone to update the mod if the source is available or there are tools you can use to try and edit your save file so it loads.

**Comment by Gwendovescry** [comment]
But the game didn't update since yesterday when it worked perfectly fine

**Comment by WittleWolfie** [comment]
I couldn't tell you. There were multiple patches around the time you reported the bug (the chain of 1.4.X hotfixes). Possibly one of those broke it.

All I can say for sure is that the blueprint causing the problem is not, and never has been, in COP, and there's a problem w/ TheSwarmFiles, which, if I remember correctly is Homebrew Archetypes. That would be Sigurd on Discord.
