### ISSUE TITLE
[Feature] glorious heat - printed version

### ISSUE THREAD

**Issue by knk101** [WittleWolfie/CharacterOptionsPlus#62]
https://www.aonprd.com/FeatDisplay.aspx?ItemName=Glorious%20Heat

Would you consider adding this version which uses half of character level? 

Provide a link to the feature on [d20 PF SRD](https://www.d20pfsrd.com/) or [AoN PRD](https://www.aonprd.com/).

**Comment by WittleWolfie** [comment]
Yeah I might though I'll exclude cantrips for sure.

**Comment by knk101** [comment]
Yeah definitely don't like the cantrip it opens up.

**Comment by WittleWolfie** [comment]
It'll be in the next release.

**Comment by WittleWolfie** [comment]
Note: as an optional setting.
