### ISSUE TITLE
[BUG] Hurtful feat has no effect

### ISSUE THREAD

**Issue by Stoltverd** [WittleWolfie/CharacterOptionsPlus#64]
**Attach a Bug Report**
[verhomir.zip](https://github.com/WittleWolfie/CharacterOptionsPlus/files/9743055/verhomir.zip)

**Describe the bug**
The 'Hurtful' feat has no in-game effect. When the feat is active, the enemy is on melee range and then gets demoralized, be it because of using the demoralize action, dazzling display or whatever... Nothing happens. It's as if the feat didn't exist.

**To Reproduce**
1. Start a battle. Make sure the 'Hurtful' feat is active.
2. Use 'Demoralize', 'Dazzling Display' or 'Cornugon Smash'
3. See error

**Expected behavior**
1. Start a battle. Make sure the 'Hurtful' feat is active.
2. Use 'Demoralize', 'Dazzling Display' or 'Cornugon Smash'
3. If the intimidation succeeded, the character uses a swift action to make an attack at full BAB.

**Screenshots**
![image](https://user-images.githubusercontent.com/19286141/194790783-8ade287a-cfeb-4bf4-b733-980f6fee91e2.png)
Note the intimidation succeded, but no extra attack was made.

**Comment by Stoltverd** [comment]
Adding an extra screenshot showing the character is in melee range:
![image](https://user-images.githubusercontent.com/19286141/194790875-ad204302-be5d-48ae-8dcc-04f340d4967a.png)

**Comment by WittleWolfie** [comment]
Beautiful bug report, appreciate it. Can you share your save file?

I can test it out tomorrow, but the log is reporting that your character does not have a swift action available:

![image](https://user-images.githubusercontent.com/399167/194792140-3a19c17e-46f0-4cb3-9b80-b7cf9d10fa0e.png)

**Comment by WittleWolfie** [comment]
I notice you also have no move action: is this the first round? If it's a surprise round you have no swift action.

**Comment by WittleWolfie** [comment]
And actually now that I notice it shows you don't have a swift on the bar either, so the main question I think is: what used your swift.

**Comment by Stoltverd** [comment]
Nothing. I should have a swift. Isn't the open hand an indication of the character having a swift?
It's my understanding that when a swift is used, it shows an icon instead of the open hand with what used the swift.
Regarding your question about the round number; I tested it in several rounds. That's why the Schir is damaged.

Here's the savefile:
[Manual_176_Gwerm_s_Mansion__20_Arodus__VIII__4715__09_24_05.zip](https://github.com/WittleWolfie/CharacterOptionsPlus/files/9746695/Manual_176_Gwerm_s_Mansion__20_Arodus__VIII__4715__09_24_05.zip)

Here's the modlist:
Allow modded achievements
Character options+
DarkCodex
Mewsifer Console
Mewsifer Console menu
Microscopic content expansion
Mod menu
Mystical mayhem
No film grain
No TeleportationCircles restrictions
Paradox deparadoxified
Puzzle skip
Spars sorcerous sundries
Tabletop Tweaks base
Tabletop Tweaks core
Tabletop Tweaks Mythic rework
Visual adjustments 2

**Comment by WittleWolfie** [comment]
Thanks. You might be correct on the swift, it's not something I've paid a lot of attention to. I'll figure out what's going on with the save :)

**Comment by Stoltverd** [comment]
I MAY have found the issue.
Hurtful line 160:
if (caster.HasSwiftAction())
          {
            Logger.NativeLog($"No swift action available.");
            return;
          }
In my limited understanding, this would return 'True' if the character HAS a swift action available.
And since it returns, then the attack is never made.

**Comment by WittleWolfie** [comment]
Wow. You are 99% right. I don't know how I missed that in testing, I swear I tested the last release build and it worked but perhaps I was testing on the wrong build. I'll put a fix out today.

**Comment by WittleWolfie** [comment]
Fix is out, thanks so much for your help! Let me know if you have any issues w/ the latest version.

**Comment by Stoltverd** [comment]
It's working like a charm!
No animation is playing for the extra attack. But I have no idea if it's intended.
Happy to help!
If you ever need someone to slow your dev process hit me up! haha
I'm a game designer. I have a little experience in C#, but I have a lot of experience in targeted testing and ad hoc testing.

**Comment by WittleWolfie** [comment]
The animation not showing is a bug but mostly I don't know how to fix it / haven't been concerned enough. It'd be nice but I think there was an issue with having a swift action attack trigger an animation, but maybe I can fix it.

**Comment by WittleWolfie** [comment]
And yes, please keep finding things and reporting :) This is a great report, very nice to work with. Usually we get "This doesn't work." or "My game is broken." xD
