### ISSUE TITLE
[BUG]Paired Opportunists with Life Bonding Friendship

### ISSUE THREAD

**Issue by knightddk** [WittleWolfie/CharacterOptionsPlus#65]
When sharing feat, teammates cannot gain the correct environment bonus.Bonus sometimes exists and sometimes does not.At the same time, if the Fighter's Tactics are satisfied, the enemy's opportunistic attack will trigger our opportunistic attack on our teammates。

**Comment by WittleWolfie** [comment]
Can you clarify: what environment bonus are you referring to?

**Comment by WittleWolfie** [comment]
Also what are you referring to with regards to "Fighter's Tactics"?

**Comment by WittleWolfie** [comment]
Also please share a log after repro: https://github.com/WittleWolfie/CharacterOptionsPlus#reporting-problems
