### ISSUE TITLE
[Feature] Arrowsong 7th level slots

### ISSUE THREAD

**Issue by DarkSonic1337** [WittleWolfie/CharacterOptionsPlus#66]
Any chance you could allow Arrowsong Archer to merge with Aeon, Azata, Demon, and Trickster mythic spellbooks when using spellbook merge mod (and similarly give it 7th level spell slots like base bard.)??

https://github.com/vikigenius/SpellbookMerge

If nothing else, just the 7th slots would be nice so I could force merge them with Toybox. (I don't know how to add higher level spell slots in toybox if that's even possible.)

**Comment by WittleWolfie** [comment]
I'm afraid not. It's too complicated & fragile.
