### ISSUE TITLE
Versions newer than 0.6 won't load [BUG]

### ISSUE THREAD

**Issue by alkdnvwoeivn** [WittleWolfie/CharacterOptionsPlus#68]
I've been using the mod for a while, but the newer releases don't load. Version 0.6.0 works fine, but anything newer gives me the red dot and !!! in UMM, plus there's no entry for Character Options + in the mod menu. I've updated UMM and TTT, and I'm running the latest game version. Has anyone else reported this problem, or is it just me?

**Comment by WittleWolfie** [comment]
Haven't heard from anyone about this. Please share logs: https://github.com/WittleWolfie/CharacterOptionsPlus#reporting-problems

**Comment by WittleWolfie** [comment]
Also out of curiosity, have you tried verifying game file integrity? Things that would cause failures to load:

1. Mismatched game code
2. Out of date ModMenu or TTT-Core

If you've updated all your mods and the game to the latest version it points to an issue w/ the game code, which could be some kind of local corruption.

**Comment by WittleWolfie** [comment]
I'm betting you are on an old version of ModMenu. Starting in 0.7.0 it requires the 1.3 release.

**Comment by alkdnvwoeivn** [comment]
Yes, that was the problem. Updated modmenu and it's working now. Not sure how I missed that update. Thanks!

**Comment by WittleWolfie** [comment]
Glad you resolved it!

**Comment by alkdnvwoeivn** [comment]
Yes, that was the problem. Updated modmenu and it's working now. Not sure how I missed that update. Thanks!
