### ISSUE TITLE
[BUG] Furious Focus feat not working on 1H weapons used with two hands

### ISSUE THREAD

**Issue by CrazedWeevil** [WittleWolfie/CharacterOptionsPlus#69]
Using the Furious Focus feat with a Bastard Sword in two hands is not working correctly. I've confirmed that the feat does work with a two handed weapon, but won't on any one handed weapon used with two hands. 

<img width="393" alt="Bastard Sword" src="https://user-images.githubusercontent.com/119804387/205502459-728eba57-eea8-4505-8d2c-a523a2241b1b.png">

<img width="391" alt="Quarterstaff" src="https://user-images.githubusercontent.com/119804387/205502472-2818f7bd-14a5-4acd-8b1a-7bade69bd5b9.png">

Enclosed log file & save game file of my current character with the feat.
[Log & Save File.zip](https://github.com/WittleWolfie/CharacterOptionsPlus/files/10148987/Log.Save.File.zip)

**Comment by WittleWolfie** [comment]
Fixed for next release (should release w/in a week).
