### ISSUE TITLE
[BUG]        Will not load with patch 2/0/5

### ISSUE THREAD

**Issue by Reguoc** [WittleWolfie/CharacterOptionsPlus#71]
**Attach a Bug Report**
https://github.com/WittleWolfie/CharacterOptionsPlus#reporting-problems

**Describe the bug**

**To Reproduce**
2. Use '....'
3. See error

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by WittleWolfie** [comment]
I cannot reproduce this and have no other reports. Please attach a bug report.

**Comment by WittleWolfie** [comment]
Without a repro or bug report I can't do anything, closing out. Please re-open if you still have problems and attach logs.
