### ISSUE TITLE
[Feature] Frostbite & Chill Touch

### ISSUE THREAD

**Issue by DarkSonic1337** [WittleWolfie/CharacterOptionsPlus#72]
**SRD Link**
Provide a link to the feature on [d20 PF SRD](https://www.d20pfsrd.com/) or [AoN PRD](https://www.aonprd.com/).

So I saw that your latest update added the shadow blindness spell. Is there a chance you could add other multi use touch spells like 

Frostbite https://www.d20pfsrd.com/magic/all-spells/f/frostbite/

and

Chill Touch https://www.d20pfsrd.com/magic/all-spells/c/chill-touch/

**Comment by WittleWolfie** [comment]
For sure. Probably be a while before I get to this but I like these.

**Comment by FrijDom** [comment]
I'd like to second this. As someone who plays a lot of magi, I'd love to have a consistent spellstrike.

**Comment by WittleWolfie** [comment]
Frostbite is done and ready for the next release.

**Comment by WittleWolfie** [comment]
Chill Touch done, also coming w/ the next release.
