### ISSUE TITLE
[BUG] Will not work with Worldcrawl or Homebrew Archtypes

### ISSUE THREAD

**Issue by jedi7000nathan** [WittleWolfie/CharacterOptionsPlus#73]
I'll let you know that this mod breaks both Worldcrawl and Homebrew Archetypes removed it and I had zero issues with Worldcrawl OR Homebrew Archetypes

**Comment by WittleWolfie** [comment]
Can you share a log and more details about what breaks?

**Comment by WittleWolfie** [comment]
Let me know if you can capture a log. Attaching a log from a separate report I missed on Discord.
[ynmmw55u.mew.zip](https://github.com/WittleWolfie/CharacterOptionsPlus/files/10210898/ynmmw55u.mew.zip)

**Comment by WittleWolfie** [comment]
Alright the WorldCrawl problem is because WC doesn't null check `LocalizedDuration` which can be null. I can fix this and probably will, but this likely means most mods that add `BlueprintAbility` will conflict w/ WC.

**Comment by WittleWolfie** [comment]
Actually I'm wrong and I have no idea why it's conflicting w/ WC. LocalizedDuration shouldn't be null in COP+ blueprints at all.

**Comment by WittleWolfie** [comment]
I can't reproduce any conflict w/ HA.

**Comment by jedi7000nathan** [comment]
I think it's likely a thing of Worldcrawl also being in there: I think you'd get the result I'm having if all three were installed at the same time. Potentially the Worldcrawl thing is causing both CO+ and HA to not work if both are installed alongside it and the culprit is the same as the one for the Worldcrawl issue

**Comment by jedi7000nathan** [comment]
Dang my logs are of the most recent play session after I had removed both mods when I found out they were causing the conflicts. I could replicate the results by reinstalling both but I don't want to risk creating a save dependency and breaking my save file again.
