### ISSUE TITLE
Weapon of Awe will not cast

### ISSUE THREAD

**Issue by 1RMR1** [WittleWolfie/CharacterOptionsPlus#75]
Hello,

The spell Weapon of Awe will not cast.

**Comment by WittleWolfie** [comment]
@1RMR1 Please provide log & save file: https://github.com/WittleWolfie/CharacterOptionsPlus#reporting-problems

**Comment by 1RMR1** [comment]
Hello,

looks like rebooting the game fixed it. It seems to be working now.
