### ISSUE TITLE
Get spells to work with Bubble Buffs.

### ISSUE THREAD

**Issue by 1RMR1** [WittleWolfie/CharacterOptionsPlus#76]
Hello,

Bubble buffs do not have these spells on the list.

**Comment by WittleWolfie** [comment]
Based on my own investigation I believe these three spells don't work:

1. Keen Edge
2. Weapon of Awe
3. Hedging Weapons

Each of these has custom actions that Bubble Buffs doesn't check for.

**Comment by biship** [comment]
This looks implemented in BubbleBuffs with https://github.com/factubsio/BubbleBuffs/pull/36

**Comment by WittleWolfie** [comment]
IIRC this fix broke at some point. If it does work lmk.
