### ISSUE TITLE
[Feature] Raging Blood feat

### ISSUE THREAD

**Issue by pheonix99** [WittleWolfie/CharacterOptionsPlus#78]
https://www.d20pfsrd.com/feats/general-feats/raging-blood

This looks extremely nifty for sorc-gishes or eldritch scion magus, especially if the 2 four round bloodrages is switches to an eight turn total meter and extra rage feats are applicable

**Comment by WittleWolfie** [comment]
I am interested in this for sure. Main concern is complexity of having this act "as blood-rage" but maybe there's a clever way to simplify that.

**Comment by pheonix99** [comment]
Make it use the bloodrage buff and add *ever more conditionals* to make the baby bloodrage level from the feat be the one that appears if that's the highest level you have?

**Comment by WittleWolfie** [comment]
Yeah that's one way I was thinking about it. But either way this will be after my 1.0 release so not thinking too hard about it right now

**Comment by pheonix99** [comment]
I've been messing around with rage and this could be a nightmare to dynamically implement because rather than do the smart thing and have one hidden buff for all the "this works on all rages" effects they add them separately to each form of rage. Still cool tho.
