### ISSUE TITLE
[BUG] Frozen caress doesn't work on every touch spells like snowball

### ISSUE THREAD

**Issue by CanMik** [WittleWolfie/CharacterOptionsPlus#80]
Hello it's me again :)

I've tested the new version, frozen caress works now with ray of frost, but still doesn't work with spells like snowball :/

**Comment by WittleWolfie** [comment]
I do not have any issues w/ Snowball. Here are instructions for a bug report: https://github.com/WittleWolfie/CharacterOptionsPlus#reporting-problems

One thing to keep in mind w/ Snowball: Frozen Caress adds a saving throw. If they pass it would have no effect.

**Comment by CanMik** [comment]
Strange it also works now for me, my bad then :/
