### ISSUE TITLE
[Feature] 'Ossuarite' Druid Archetype

### ISSUE THREAD

**Issue by theKross** [WittleWolfie/CharacterOptionsPlus#85]
Is it possible to add the archetype 'Ossuarite' for the Druid ?

https://www.d20pfsrd.com/classes/core-classes/druid/archetypes/forest-guardian-press-druid-archetypes/ossuarite-druid-archetype/

*Dream of a Evil Ossuarite/Winter Witch Lich*

**Comment by WittleWolfie** [comment]
That is a _tough_ one. The biggest thing is going be visuals, but if you can get a list of skeletal models in the game that's a good start.

This is definitely a stretch but it sounds really cool so, I'll think about it.

**Comment by WittleWolfie** [comment]
I still like the idea, but this is a ton of work so I'm flagging as a Maybe. I'm preparing for my second run of the game so this is 6+ months out if I'm going to do it.
