### ISSUE TITLE
Eldritch Heritage behaving oddly with bloodrager.

### ISSUE THREAD

**Issue by pheonix99** [WittleWolfie/CharacterOptionsPlus#87]
For a lark, decided to see if I could take Eldritch Heritage on a bloodrager.

Appear to meet all the prerequisites for the selector but no options permitted.

Not sure what intended behavior is overall but if supposed to be blocked on bloodrager should probably block on feature.

Might be the known issue with TTT-Base and second bloodline I suppose?

**Comment by WittleWolfie** [comment]
Can you share a save file?

**Comment by pheonix99** [comment]
Uh, I got like 20+ mods installed.

I don't think I can usefully give one.

**Comment by pheonix99** [comment]
I was bloodrager 3 with celestial bloodline, actually just wanted to see if it was allowed and got that.

**Comment by pheonix99** [comment]
Is the skill focus requirement from TT implemented?

I forgot about that.

**Comment by WittleWolfie** [comment]
Yes they require skill focus.

**Comment by pheonix99** [comment]
The problem is on my end, with a side of it being hard to see that because of how the game deals  with selectors where you can't take any options.

**Comment by pheonix99** [comment]
Maybe add an OR prereq for having an applicable skill focus to the selector?

Or the description that works too.

**Comment by WittleWolfie** [comment]
I like the OR pre-req.
