### ISSUE TITLE
[BUG] Hedging Weapons lasts an incorrect amount of time

### ISSUE THREAD

**Issue by Woffingshire** [WittleWolfie/CharacterOptionsPlus#92]
The spell description for Hedging Weapons states it's duration as 1 minute/level, however whenever I cast it as a level 4 paladin, the duration for it is only 1 minute.

**Comment by WittleWolfie** [comment]
This is WAI. I don't think they call it out in the game text, but [Paladin](https://www.d20pfsrd.com/classes/core-classes/paladin/) has a CL penalty of -3:

> Through 3rd level, a paladin has no caster level. At 4th level and higher, her caster level is equal to her paladin level – 3.

**Comment by Woffingshire** [comment]
Ah, I see. Im a dunce. Sorry
