### ISSUE TITLE
[Feature] Mythic Furious Focus

### ISSUE THREAD

**Issue by pheonix99** [WittleWolfie/CharacterOptionsPlus#93]
[This baby.](https://www.d20pfsrd.com/alternative-rule-systems/mythic/mythic-feats/furious-focus-mythic/)

So incredibly hilarious on critical cascade builds.

**Comment by WittleWolfie** [comment]
The game doesn't have an implementation of Mythic Power as a resource does it? I've only just hit mythic stuff and it seems like everything is kind of independently resourced.

I'm like 90% sure the way I implemented Furious Focus, it would apply to an AOO iff it was your first attack that round. So this could just make that not count at all as "first attack" and always apply to AOO, but unsure about the "all attacks for one round" bit. Maybe limit to 1/2 Mythic Level per day, min 1?

**Comment by pheonix99** [comment]
No it doesn't have an Mythic Power implementation.

I would just completely ditch the pay mythic power component. This is godtier on a very strong party build without it anyway.
