### ISSUE TITLE
[BUG] Weapon of Awe not castable on ranged weapons

### ISSUE THREAD

**Issue by IanJlafferty** [WittleWolfie/CharacterOptionsPlus#94]
**Describe the bug**
Can not cast Weapon of Awe on ranged weapons. It says that I am try to cast it on natural weapon instead and does not work.

**To Reproduce**
1. Have a caster with Weapon of Awe
2. Attempt to cast on character with ranged weapon
3. See error

**Expected behavior**
I expect to be able to cast Weapon of Awe on a ranged weapon.

**Comment by WittleWolfie** [comment]
If you can please share a save file.

**Comment by IanJlafferty** [comment]
I will do so once I am home. I also now realize that my late night sleepy self did not, that the bug could be my fault due to the mods being run alongside yours.

**Comment by IanJlafferty** [comment]
Here is my save.
[Manual_275_Treasure_Island__1_Rova__IX__4715__06_13_25.zip](https://github.com/WittleWolfie/CharacterOptionsPlus/files/10376868/Manual_275_Treasure_Island__1_Rova__IX__4715__06_13_25.zip)

As well as the mods I use
![ModList](https://user-images.githubusercontent.com/6034245/211410289-1c44eda3-ad31-4550-a3f5-03362ddfd779.PNG)

**Comment by WittleWolfie** [comment]
I should get to this by the weekend. I don't think it is a conflict but we'll see.
