### ISSUE TITLE
[BUG] Shared Spells Feature Breaks Brown Fur Transmuter Share Transmutation Ability

### ISSUE THREAD

**Issue by Vaeliorin** [WittleWolfie/CharacterOptionsPlus#96]
When the Share Spells feather is turned on, Brown Fur Transmuter is unable to share transmutation spells (other than with a pet, it seems...it would let me cast personal spells on Bismuth despite him not being equipped on my Brown Fur Transmuter.)

Turning it off restored the Share Transmutation ability to how it normally functions.

**Comment by WittleWolfie** [comment]
Fixed in 1.1.1 (coming soon).
