### ISSUE TITLE
[BUG] Weapon Of Awe Doesn't Cast While Mounted

### ISSUE THREAD

**Issue by Vaeliorin** [WittleWolfie/CharacterOptionsPlus#99]
Can't cast Weapon of Awe while mounted, even on the caster (I though it might be a range issue at first.)  The animation starts, but never finishes, and the spell never casts.  Dismounting allows it to work just fine, so it's not a huge issue.

**Comment by WittleWolfie** [comment]
Well that was dumb. Turns out they didn't implement all the spellcasting animations while mounted, so spells / abilities using the `EnchantWeapon` animation fail. Fixed in next release.
